export const STEP_NAMES = ["engagement", "qualify", "committee", "crm", "outreach", "approval", "send", "reply", "call", "deal"] as const;
export type StepName = (typeof STEP_NAMES)[number];
export type StepStatus = "pending" | "running" | "done" | "failed" | "skipped" | "awaiting_approval";

export interface PipelineEvent {
  id: number;
  runId: string;
  step: StepName | "run" | "webhook" | "batch" | "work";
  status: StepStatus;
  data?: unknown;
  error?: string;
  timestamp: string;
}

export interface EngagementEvent {
  type: "newsletter_click" | "site_visit";
  domain: string;
  url?: string;
  title?: string;
  contactEmail?: string;
  newsletterId?: string;
  issueId?: number;
  subscriberId?: number;
  occurredAt?: string;
}

export interface RunInput { domain?: string; event?: EngagementEvent }

export interface EngagementSignal { source: "newsletter" | "website" | "link"; description: string; url?: string; at?: string }
export interface EngagementOutput { domain: string; companyName?: string; signals: EngagementSignal[] }

export interface CompanyProfile { domain: string; name: string; industry?: string; employeeCount?: string; linkedinUrl?: string; description?: string }
/** A Radar competitor the prospect appears to use, with battle-card talking points. */
export interface CompetitorHit { name: string; domain?: string; evidence: string; talkingPoints: string[] }
export interface QualifyOutput {
  company: CompanyProfile; score: number; qualified: boolean; reasons: string[];
  competitor?: CompetitorHit;
  /** Score changes the desk learned from past approve/reject decisions. */
  learned?: string[];
}

export interface CommitteeMember {
  firstName: string; lastName: string; email?: string; title?: string; seniority?: string;
  department?: string; linkedinUrl?: string; role: "economic_buyer" | "champion" | "influencer" | "user";
}
export interface CommitteeOutput { members: CommitteeMember[] }

export interface CrmOutput { listId: number; companyId?: number | null; created: number; updated: number; contactIds: Record<string, number> }

export interface DraftMessage {
  contactEmail: string; channel: "email" | "linkedin" | "call_script"; subject?: string; body: string;
  /** "graph8" = generated by the graph8 API; "template" = local fallback when generation failed. */
  source?: "graph8" | "template";
}
export interface OutreachOutput { drafts: DraftMessage[] }

export interface ApprovalOutput {
  approvalId: string; decision: "approve" | "reject"; decidedAt: string; edited?: number; drafts?: DraftMessage[];
  /** Where the human decided: the dashboard or a reply in graph8 Work. */
  via?: "dashboard" | "graph8 Work";
}
export interface SendOutput { sequenceId?: string; sent: { contactEmail: string; channel: string; status: string }[]; outbox: Record<string, unknown>[] }
export interface ReplyOutput {
  replies: { contactEmail: string; inbound?: string; intent?: "interested" | "not_interested" | "question" | "out_of_office"; draft: string }[];
}
export interface CallOutput { calls: { contactEmail: string; outcome: string; grade?: number; script?: string }[] }
export interface DealOutput { dealId: string; name: string; amount?: number; nextBestStep: string; taskIds: string[] }

export interface PipelineContext {
  runId: string;
  input: RunInput;
  engagement?: EngagementOutput;
  qualify?: QualifyOutput;
  committee?: CommitteeOutput;
  crm?: CrmOutput;
  outreach?: OutreachOutput;
  approval?: ApprovalOutput;
  send?: SendOutput;
  reply?: ReplyOutput;
  call?: CallOutput;
  deal?: DealOutput;
}

/** Thrown by stubbed steps in live mode; the orchestrator records it as "skipped". */
export class StepNotImplemented extends Error {
  constructor(public endpoints: string[]) {
    super("Not implemented yet (live mode)");
  }
}

/** Thrown when a step deliberately stops the run (e.g. company not qualified, send rejected). */
export class StopPipeline extends Error {
  /** Optional step output to keep on the "skipped" event (e.g. the score of an unqualified company). */
  constructor(message: string, public data?: object) {
    super(message);
  }
}

/** Thrown when one step can't run (e.g. missing config) but later steps still should. */
export class SkipStep extends Error {}
